### PR TITLE
Request tumblr over https

### PR DESCRIPTION
**Pull request by nathanmyles**
- making the tumblr requests over http can casue issues if the page is being
  loaded with https

### CODE REVIEW

**Comment by jamiew** [comment]
Thanks!

**Comment by nathanmyles** [comment]
Thanks for the quick merge! Any Idea when this might get released to the gem?

**Comment by jamiew** [comment]
I'm having some issues resetting by rubygems.org account so I can publish a new version (it's been a few years) but I will keep you posted!

Did some misc cleanup and bumped version here https://github.com/jamiew/omniauth-tumblr/tree/1.2

**Comment by jamiew** [comment]
Should be up now – v 1.2

**Comment by nathanmyles** [comment]
Awesome! Thanks!

**Pull request merged**
